package com.stabilise.util.concurrent.task2;

import java.util.function.LongUnaryOperator;

/**
 * A {@code BadReportStrategyException} being thrown indicates that a {@code
 * ReportStrategy} generated by {@link
 * ReportStrategy#manual(LongUnaryOperator)} has produced an illegal value.
 */
public class BadReportStrategyException extends RuntimeException {
    private static final long serialVersionUID = 1L;
    
    BadReportStrategyException() {}
}
